### ISSUE TITLE
Cannot Import 'safe_join' from 'flask.helpers'

### ISSUE THREAD

**Issue by wakaru44** [pbatey/flask-api-example#1]
There is an ImportError while running 'flask run', using Flask==2.2.2.

`ImportError: cannot import name 'safe_join' from 'flask.helpers' (/env/lib/python3.9/site-packages/flask/helpers.py)`

safe_join was removed from flask.helpers in flask version 2.1.0 released on 28-03-2022

From flask [Version 2.1.0 CHANGES.rst](https://github.com/pallets/flask/blob/cb4f7425435c39a85c3ed17e395677597d9aaf31/CHANGES.rst#version-210)

> safe_join is removed, use werkzeug.utils.safe_join instead.

I solved the issue downgrading flask, but I thought it would be worth letting you know.

(I'm not sure what's the best place, so I'll open the issue in your other repo too. Thank you soo much for writting and publishing this software ❤️ )

**Comment by pbatey** [comment]
Thanks for the update! I'll check out updating to use werkzeug.utils.safe_join.

**Comment by pbatey** [comment]
This is now fixed and available with [flask-staticdirs 1.0.1](https://pypi.org/project/flask-staticdirs/1.0.1/).

**Comment by wakaru44** [comment]
💥 🏅  Amazing! thank you very much for the super quick response 😄
